/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.courseproject;

import java.util.List;
import java.util.stream.Collectors;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bahaa
 */
public class addEditInstructors extends javax.swing.JFrame {

    /**
     * Creates new form addEditInstructors
     */
    public addEditInstructors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TFieldN = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TFieldC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        TFieldN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFieldNActionPerformed(evt);
            }
        });

        jButton1.setText("ADD");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        TFieldC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFieldCActionPerformed(evt);
            }
        });

        jLabel2.setText("Course");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton1)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFieldN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFieldC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFieldNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFieldNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFieldNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TFieldCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFieldCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFieldCActionPerformed
    public addEditInstructors(instructorManagement instructorManagement) {
    this.instructorManagement = instructorManagement;
}
// داخل فئة addEditInstructors

    private instructorManagement instructorManagement;

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
    // الحصول على القيم من حقول النص
    String name = TFieldN.getText().trim();
    String course = TFieldC.getText().trim();

    // التحقق من أن الحقول ليست فارغة
    if (name.isEmpty() || course.isEmpty()) {
        System.out.println("Both name and course must be provided.");
        return;
    }

    // قراءة البيانات من الملف النصي لتحديد آخر معرّف (ID) وتحديد المعرف المفقود إن وجد
    List<Instructor> instructors = Instructor.readFromFile();
    int newId = 1;

    if (!instructors.isEmpty()) {
        // الحصول على قائمة من المعرفات الحالية
        List<Integer> ids = instructors.stream().map(Instructor::getId).sorted().collect(Collectors.toList());

        // العثور على أول معرف مفقود
        for (int i = 0; i < ids.size(); i++) {
            if (ids.get(i) != i + 1) {
                newId = i + 1;
                break;
            }
        }

        // إذا لم يتم العثور على معرف مفقود، قم بتعيين معرف جديد أعلى بواحد من أعلى معرف موجود
        if (newId == 1 && ids.get(ids.size() - 1) == ids.size()) {
            newId = ids.size() + 1;
        }
    }

    // إنشاء مدرس جديد
    Instructor newInstructor = new Instructor(name, course, newId);
    Instructor.writeToFile(newInstructor);

    // مسح حقول النص بعد الإدخال
    TFieldN.setText("");
    TFieldC.setText("");

    // إعادة فتح وتحديث نافذة instructorManagement
    openInstructorManagement();

    // إغلاق نافذة الإضافة بعد عملية الإضافة
    dispose();

    System.out.println("Instructor added successfully with ID: " + newId);
}

private void openInstructorManagement() {
    // التأكد من أن النافذة موجودة (Singleton)
    instructorManagement instructorMgmt = instructorManagement.getInstance();
    instructorMgmt.updateInstructorTable(); // تحديث الجدول
    instructorMgmt.setVisible(true); // إظهار النافذة


    }//GEN-LAST:event_jButton1MousePressed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFieldC;
    private javax.swing.JTextField TFieldN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
